MODE='DEV'
DEBUG = True
SECRET_KEY=''
SECURITY_PASSWORD_SALT=''
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = ""

AWS_ACCESS_KEY_ID=''
AWS_SECRET_ACCESS_KEY=''

# Live keys
#PAYPAL_CLIENT_ID=''
#PAYPAL_SECRET=''

# Dev keys
PAYPAL_CLIENT_ID=''
PAYPAL_SECRET=''
